### ISSUE TITLE
cross-link intended?

### ISSUE THREAD

**Issue by nbehrnd** [novoid/2011-04-tagstore-formal-experiment#1]
Both this project as well as the sibling [January experiment](https://github.com/novoid/2011-01-tagstore-formal-experiment) point to [tagstore.org](http://tagstore.org/).  Yet by today, this address is resolved to a web site with only little visible conceptual overlap to your `filetags` script:

![2022-03-22_tagstore](https://user-images.githubusercontent.com/19709084/159472610-aebcc75f-2ca9-4565-8ef6-4b731dbaa873.png)

**Comment by novoid** [comment]
Thanks for the reminder. I obviously overlooked old links. I hope I fixed the remaining ones. The URL is https://karl-voit.at/tagstore/ and the tagstore.org domain was abandoned after 2014.
